apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tiger-app
  template:
    metadata:
      labels:
        app: tiger-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
